### ISSUE TITLE
Kibana dashboards

### ISSUE THREAD

**Issue by obp3ter** [felix-lessoer/qbeat#13]
I don't know what I did wrong, but none of the Kibana dashboards work for me. The beat itself does, although it wasn't easy to set it up in a docker container.
![image](https://github.com/felix-lessoer/qbeat/assets/15703843/cbd1eb5f-b995-4132-af6a-9c0ade498b8b)

**Comment by felix-lessoer** [comment]
Hi @obp3ter 
the issue seems to be a mapping issue for the index. It expects some fields like `qmgr` to be keyword. However based on the error it looks like it is the default mapping (text).
You can either change the mapping in the template and reload the data.. 
Or you simply edit the visualization to use e.g. qmgr.keyword which should exist for the default mapping.

**Comment by obp3ter** [comment]
Yeah. that was it. Thanks
